---
- hosts: vps2
  gather_facts: no  # 避免收集节点信息, 蛮耗时的.
  remote_user: root


  tasks:

    - name: echo date 
      command: date 
      register: date_output 

    - name: show results?
      debug: msg="{{date_output.stdout}}"


    - command: "echo {{item}}"
      register: result
      with_items: [1, 2]
    - debug:
        var: result
